#ifndef SPHINCS_PARAMS_H
#define SPHINCS_PARAMS_H

#define SPX_N 20
#include "custom_params.h"

/* Disable broken namespace system */
#define SPX_NAMESPACE(name) name

#define SPX_D 1
#define SPX_H 1
#define SPX_A 1
#define SPX_K 1
#define SPX_TREE_HEIGHT 1
#define SPX_FORS_HEIGHT 1
#define SPX_FORS_TREES 1

#define SPX_FORS_MSG_BYTES 1
#define SPX_FORS_BYTES (SPX_FORS_TREES * (SPX_FORS_HEIGHT * SPX_N))
#define SPX_PK_BYTES (2 * SPX_N)
#define SPX_BYTES (SPX_FORS_BYTES + SPX_D * (SPX_WOTS_BYTES + SPX_TREE_HEIGHT * SPX_N))
#define SPX_SK_BYTES (4 * SPX_N + SPX_PK_BYTES + SPX_BYTES)
#define SPX_ADDR_BYTES 32
#define SPX_SLICE_BYTES 105

#define SPX_WOTS_W 256
#define SPX_WOTS_LOGW 8
#define SPX_WOTS_LEN1 ((8*SPX_N + SPX_WOTS_LOGW - 1) / SPX_WOTS_LOGW)
#define SPX_WOTS_LEN2 (SPX_WOTS_LEN1 + 1)
#define SPX_WOTS_LEN (SPX_WOTS_LEN1 + SPX_WOTS_LEN2)
#define SPX_WOTS_BYTES (SPX_WOTS_LEN * SPX_N)

#define SPX_OFFSET_LAYER 0
#define SPX_OFFSET_TREE 1
#define SPX_OFFSET_TYPE 9
#define SPX_OFFSET_KP_ADDR 12
#define SPX_OFFSET_CHAIN_ADDR 16
#define SPX_OFFSET_HASH_ADDR 20
#define SPX_OFFSET_TREE_HGT 24
#define SPX_OFFSET_TREE_INDEX 28

#define SPX_ADDR_TYPE_WOTS 0
#define SPX_ADDR_TYPE_WOTSPK 1
#define SPX_ADDR_TYPE_HASHTREE 2
#define SPX_ADDR_TYPE_FORS_TREE 3
#define SPX_ADDR_TYPE_FORS_ROOTS 4
#define SPX_ADDR_TYPE_WOTSPRF 5

#endif
